# Generated by Django 6.0.6 on 2026-06-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("feature_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("category_name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("linkRewrite", models.CharField(blank=True, max_length=255)),
                ("itemsCount", models.IntegerField(default=0)),
                (
                    "parentId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="zoomos.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=255)),
                ("typePrefix", models.CharField(blank=True, max_length=100)),
                ("linkRewrite", models.CharField(blank=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("priceCurrency", models.CharField(default="BYN", max_length=10)),
                ("status", models.IntegerField(default=1)),
                ("isNew", models.IntegerField(default=1)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("bar", models.CharField(blank=True, max_length=100)),
                ("fullDescriptionHTML", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zoomos.category",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zoomos.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("values", models.JSONField(default=list)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="zoomos.product",
                    ),
                ),
            ],
        ),
    ]
